### ISSUE TITLE
启动插件时出现类型错误

### ISSUE THREAD

**Issue by Fui-Reconk** [GuGuMur/nonebot-plugin-skland-arksign#20]
>Traceback (most recent call last):
  File "/root/Pallas-Bot/bot.py", line 26, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "/root/Pallas-Bot/lib/python3.9/site-packages/nonebot/plugin/load.py", line 130, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/root/Pallas-Bot/lib/python3.9/site-packages/nonebot/plugin/load.py", line 64, in load_all_plugins
    return manager.load_all_plugins()
  File "/root/Pallas-Bot/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 176, in load_all_plugins
    return set(
  File "/root/Pallas-Bot/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 177, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
 File "/root/Pallas-Bot/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 142, in load_plugin
    module = importlib.import_module(name)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/root/Pallas-Bot/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 242, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/Pallas-Bot/lib/python3.9/site-packages/nonebot_plugin_skland_arksign/__init__.py", line 12, in <module>
    from .command import skland as skland
  File "/root/Pallas-Bot/lib/python3.9/site-packages/nonebot_plugin_skland_arksign/command.py", line 13, in <module>
    from .sched import sched_sign
  File "/root/Pallas-Bot/lib/python3.9/site-packages/nonebot_plugin_skland_arksign/sched.py", line 10, in <module>
    from .utils import run_sign
  File "/root/Pallas-Bot/lib/python3.9/site-packages/nonebot_plugin_skland_arksign/utils.py", line 121, in <module>
    url: str, method: Literal["get", "post"], body: dict | None, old_header: dict, sign_token: str
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType

**Comment by Fui-Reconk** [comment]
这个问题好像是因为3.9的Python不支持导致的

**Comment by GuGuMur** [comment]
是这样的 这种语法糖在[PEP 0604](https://peps.python.org/pep-0604/) （Python 3.10）中支持
