### ISSUE TITLE
[Bug]: TypeError: AsyncConnectionPool.__init__() got an unexpected keyword argument 'socket_options'

### ISSUE THREAD

**Issue by aazhaoyoukino** [GuGuMur/nonebot-plugin-skland-arksign#35]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读插件的 README
- [X] 我的Python版本满足>= 3.10
- [X] 我已经将插件和机器人环境依赖都安装到了推荐/最新版本
- [X] 我确定指令输入并无错误
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### 运行环境

Ubuntu

### Nonebot 2 版本

2.0.1

### 重现步骤

什么都没动过突然出现了这个错误，经检查和问chatgpt应该不是插件的错误是我自己的问题，但是由于是小白再加上ai给的方法都没用，只能在这里问问
立即执行签到操作完成！
签到失败：AsyncConnectionPool.__init__() got an unexpected keyword argument 'socket_options'

### 期望的结果是什么？

.

### 实际的结果是什么？

.

### 日志记录（可选）

```python
TypeError: AsyncConnectionPool.__init__() got an unexpected keyword argument 'socket_options'
_GatheringFuture exception was never retrieved
future: <_GatheringFuture finished exception=TypeError("AsyncConnectionPool.__init__() got an unexpected keyword argument 'socket_options'")>
Traceback (most recent call last):
  File "/root/yukino/.venv/lib/python3.10/site-packages/nonebot_plugin_steam_game_status/__init__.py", line 81, in get_status
    async with AsyncClient(verify=False) as client:
  File "/root/yukino/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1397, in __init__
    self._transport = self._init_transport(
  File "/root/yukino/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1445, in _init_transport
    return AsyncHTTPTransport(
  File "/root/yukino/.venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 275, in __init__
    self._pool = httpcore.AsyncConnectionPool(
TypeError: AsyncConnectionPool.__init__() got an unexpected keyword argument 'socket_options'
```

**Comment by GuGuMur** [comment]
查了一下，<code>pip install httpx==0.24.1</code>可能有效（？

**Comment by AzideCupric** [comment]
httpx版本太低了吧

**Comment by aazhaoyoukino** [comment]
> 查了一下，`pip install httpx==0.24.1`可能有效（？

试了还是不行，准备重装系统重新装了，添麻烦了兄弟
