### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by sapphire159** [GuGuMur/nonebot-plugin-skland-arksign#37]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读插件的 README
- [X] 我的Python版本满足>= 3.10
- [X] 我已经将插件和机器人环境依赖都安装到了推荐/最新版本
- [X] 我确定指令输入并无错误
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### 运行环境

Windows (64)

### Nonebot 2 版本

2.0.1

### 重现步骤

根据依赖安装插件后报错，无法启动seesion-saa

### 期望的结果是什么？

正常启动

### 实际的结果是什么？

ImportError: cannot import name 'SupportedAdapter' from 'nonebot_plugin_session.const' (C:\Users\Administrator\QQ-bot1\.venv\lib\site-packages\nonebot_plugin_session\const.py)

> 

### 日志记录（可选）

```python
11-28 00:32:42 [ERROR] nonebot | Failed to import "nonebot_plugin_session_saa"
Traceback (most recent call last):
  File "<string>", line 22, in <module>
  File "C:\Users\Administrator\QQ-bot1\.venv\lib\site-packages\nonebot\plugin\load.py", line 130, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\Users\Administrator\QQ-bot1\.venv\lib\site-packages\nonebot\plugin\load.py", line 64, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\QQ-bot1\.venv\lib\site-packages\nonebot\plugin\manager.py", line 176, in load_all_plugins
    return set(
  File "C:\Users\Administrator\QQ-bot1\.venv\lib\site-packages\nonebot\plugin\manager.py", line 177, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\Administrator\QQ-bot1\.venv\lib\site-packages\nonebot\plugin\manager.py", line 142, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Administrator\QQ-bot1\.venv\lib\site-packages\nonebot\plugin\manager.py", line 242, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Administrator\QQ-bot1\.venv\lib\site-packages\nonebot_plugin_session_saa\__init__.py", line 34, in <module>
    from nonebot_plugin_session.const import SupportedAdapter, SupportedPlatform
ImportError: cannot import name 'SupportedAdapter' from 'nonebot_plugin_session.const' (C:\Users\Administrator\QQ-bot1\.venv\lib\site-packages\nonebot_plugin_session\const.py)
```

### 补充说明（可选）

已发现为 nonebot_plugin_session更新0.2.2版本后，删除了nonebot_plugin_session\const.py中SupportedAdapter这部分的代码，导致无法启动。根据0.2.1版本内容手动添加后可以正常使用。

**Comment by sapphire159** [comment]
发错地方了，要发到saa里才对，开了一堆git搞错了。
