### ISSUE TITLE
[Bug]: 报错405 NOT ALLOWED

### ISSUE THREAD

**Issue by yytphilip** [GuGuMur/nonebot-plugin-skland-arksign#60]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读插件的 README
- [X] 我的Python版本满足>= 3.10
- [X] 我已经将插件和机器人环境依赖都安装到了推荐/最新版本
- [X] 我确定指令输入并无错误
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### 运行环境

Windows (64)

### Nonebot 2 版本

2.0.1

### 重现步骤

自动签到及手动签到，以及更新token后再签到都会报错

### 期望的结果是什么？

正常签到

### 实际的结果是什么？

签到失败：Client error '405 Not Allowed' for url 'https://zonai.skland.com/api/v1/game/player/binding'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405

**Comment by GuGuMur** [comment]
说实话 没见过报这个错（

1. 建议重新绑定一下账号，重新生成一套token
2. 在 `signin.py` 下的 `get_timestamp()` 、 `get_binding_list()`用print/logger检查一下输出，如果是`get_timestamp()`出问题就参照 README 把`skland_use_web_timestamp`改成 `False `，如果是 `get_binding_list()` 出问题烦请贴一下输出日志（把隐私信息隐藏一下）

**Comment by yytphilip** [comment]
> 说实话 没见过报这个错（
> 
> 1. 建议重新绑定一下账号，重新生成一套token
> 2. 在 `signin.py` 下的 `get_timestamp()` 、 `get_binding_list()`用print/logger检查一下输出，如果是`get_timestamp()`出问题就参照 README 把`skland_use_web_timestamp`改成 `False `，如果是 `get_binding_list()` 出问题烦请贴一下输出日志（把隐私信息隐藏一下）


以下为错误日志：
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\chun3\bot.py", line 21, in <module>
    nonebot.run()
  File "C:\Users\Administrator\Desktop\chun3\.venv\lib\site-packages\nonebot\__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\chun3\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "C:\Users\Administrator\Desktop\chun3\.venv\lib\site-packages\uvicorn\main.py", line 577, in run
    server.run()
  File "C:\Users\Administrator\Desktop\chun3\.venv\lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Program Files\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Program Files\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\Desktop\chun3\.venv\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
  File "C:\Users\Administrator\Desktop\chun3\.venv\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\chun3\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\chun3\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 825, in simple_run
    await handler(
  File "C:\Users\Administrator\Desktop\chun3\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\Administrator\Desktop\chun3\.venv\lib\site-packages\nonebot_plugin_skland_arksign\command.py", line 301, in signin
    sign_res = await run_signin(uid=result.uid, token=result.token)
> File "C:\Users\Administrator\Desktop\chun3\.venv\lib\site-packages\nonebot_plugin_skland_arksign\signin.py", line 168, in run_signin
    return await _run_signin(uid, token)
  File "C:\Users\Administrator\Desktop\chun3\.venv\lib\site-packages\nonebot_plugin_skland_arksign\signin.py", line 162, in _run_signin
    binding_list = await get_binding_list(cred_resp)
  File "C:\Users\Administrator\Desktop\chun3\.venv\lib\site-packages\nonebot_plugin_skland_arksign\signin.py", line 107, in get_binding_list
    response.raise_for_status()
  File "C:\Users\Administrator\Desktop\chun3\.venv\lib\site-packages\httpx\_models.py", line 761, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '405 Not Allowed' for url 'https://zonai.skland.com/api/v1/game/player/binding'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405

**Comment by GuGuMur** [comment]
（没有什么头猪）

https://github.com/GuGuMur/nonebot-plugin-skland-arksign/blob/6881abecf695224b174f79fce88c952e7fa0dbdc/nonebot_plugin_skland_arksign/signin.py#L102-L108

麻烦将此处的代码更改为：
```python
    async with AsyncClient() as client:
        response = await client.get(
            CONSTANTS.BINDING_URL,
            headers=get_sign_header(CONSTANTS.BINDING_URL, "get", None, headers, cred_resp["token"], timestamp),
        )
        response = response.json()
        print(response)
```

然后将 print 的结果附上来orz

（如果可以的话，麻烦将这样操作之后还报错的那些位置都进行类似操作，这个情况确实是没见过，没有输出结果也不知道yjwl抽了什么疯）

**Comment by yytphilip** [comment]
修改此处代码后，控制台报错如下，没有print内容输出×

```PowerShell
07-29 20:44:16 [DEBUG] nonebot | Plugin-Alconna | Alconna::skland 对 "skland signin @@" 的解析结果是 (matched=True, header_match=(origin='skland' result='skland' matched=True groups={}), subcommands={'signin': (value=Ellipsis args={'identifier': '@@'} options={} subcommands={})}, other_args={'identifier': '@@'})
07-29 20:44:16 [INFO] nonebot | Event will be handled by AlconnaMatcher(type='', module=nonebot_plugin_skland_arksign.command, lineno=25)
07-29 20:44:16 [DEBUG] nonebot | Running AlconnaMatcher(type='', module=nonebot_plugin_skland_arksign.command, lineno=25)
07-29 20:44:16 [DEBUG] nonebot | Running handler Dependent(call=add, parameterless=(Depends(Dependent(call=_arparma_check), use_cache=False),))
07-29 20:44:16 [DEBUG] nonebot | Handler Dependent(call=add, parameterless=(Depends(Dependent(call=_arparma_check), use_cache=False),)) skipped
07-29 20:44:16 [DEBUG] nonebot | Running handler Dependent(call=bind, parameterless=(Depends(Dependent(call=_arparma_check), use_cache=False),))
07-29 20:44:16 [DEBUG] nonebot | Handler Dependent(call=bind, parameterless=(Depends(Dependent(call=_arparma_check), use_cache=False),)) skipped
07-29 20:44:16 [DEBUG] nonebot | Running handler Dependent(call=del_, parameterless=(Depends(Dependent(call=_arparma_check), use_cache=False),))
07-29 20:44:16 [DEBUG] nonebot | Handler Dependent(call=del_, parameterless=(Depends(Dependent(call=_arparma_check), use_cache=False),)) skipped
07-29 20:44:16 [DEBUG] nonebot | Running handler Dependent(call=list_, parameterless=(Depends(Dependent(call=_arparma_check), use_cache=False), Depends(Dependent(call=skland_session_extract), use_cache=True)))
07-29 20:44:16 [DEBUG] nonebot | Handler Dependent(call=list_, parameterless=(Depends(Dependent(call=_arparma_check), use_cache=False), Depends(Dependent(call=skland_session_extract), use_cache=True))) skipped
07-29 20:44:16 [DEBUG] nonebot | Running handler Dependent(call=update, parameterless=(Depends(Dependent(call=_arparma_check), use_cache=False), Depends(Dependent(call=skland_session_extract), use_cache=True)))
07-29 20:44:16 [DEBUG] nonebot | Handler Dependent(call=update, parameterless=(Depends(Dependent(call=_arparma_check), use_cache=False), Depends(Dependent(call=skland_session_extract), use_cache=True))) skipped
07-29 20:44:16 [DEBUG] nonebot | Running handler Dependent(call=signin_all, parameterless=(Depends(Dependent(call=_arparma_check), use_cache=False),))
07-29 20:44:16 [DEBUG] nonebot | Handler Dependent(call=signin_all, parameterless=(Depends(Dependent(call=_arparma_check), use_cache=False),)) skipped
07-29 20:44:16 [DEBUG] nonebot | Running handler Dependent(call=signin, parameterless=(Depends(Dependent(call=_arparma_check), use_cache=False),))
07-29 20:44:17 [ERROR] nonebot_plugin_skland_arksign | 签到失败：Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\chun3\bot.py", line 21, in <module>
    nonebot.run()
  File "C:\Users\Administrator\Desktop\chun3\.venv\lib\site-packages\nonebot\__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\chun3\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "C:\Users\Administrator\Desktop\chun3\.venv\lib\site-packages\uvicorn\main.py", line 577, in run
    server.run()
  File "C:\Users\Administrator\Desktop\chun3\.venv\lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Program Files\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Program Files\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\Desktop\chun3\.venv\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
  File "C:\Users\Administrator\Desktop\chun3\.venv\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\chun3\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\chun3\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 825, in simple_run
    await handler(
  File "C:\Users\Administrator\Desktop\chun3\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\Administrator\Desktop\chun3\.venv\lib\site-packages\nonebot_plugin_skland_arksign\command.py", line 301, in signin
    sign_res = await run_signin(uid=result.uid, token=result.token)
> File "C:\Users\Administrator\Desktop\chun3\.venv\lib\site-packages\nonebot_plugin_skland_arksign\signin.py", line 172, in run_signin
    return await _run_signin(uid, token)
  File "C:\Users\Administrator\Desktop\chun3\.venv\lib\site-packages\nonebot_plugin_skland_arksign\signin.py", line 165, in _run_signin
    binding_list = await get_binding_list(cred_resp)
  File "C:\Users\Administrator\Desktop\chun3\.venv\lib\site-packages\nonebot_plugin_skland_arksign\signin.py", line 108, in get_binding_list
    response = response.json()
  File "C:\Users\Administrator\Desktop\chun3\.venv\lib\site-packages\httpx\_models.py", line 764, in json
    return jsonlib.loads(self.content, **kwargs)
  File "C:\Program Files\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by yytphilip** [comment]
仍然报相同错误×不知道啥原因

**Comment by GuGuMur** [comment]
（挠头）从客户端那能签到成功吗（

**Comment by yytphilip** [comment]
客户端可以签到 
重新绑定了账号，清空列表重新绑定账号，以及重启×都没用

**Comment by GuGuMur** [comment]
1. 绑的uid是不是游戏里那串数字（
2. 问一下客户端版本号（设置->关于森空岛），插件当前模拟的是`1.5.1`

**Comment by GuGuMur** [comment]
https://github.com/GuGuMur/nonebot-plugin-skland-arksign/blob/6881abecf695224b174f79fce88c952e7fa0dbdc/nonebot_plugin_skland_arksign/constants.py#L4-L27

可以考虑改成我这里抓到的新数据：
```python
@dataclass(frozen=True)
class _CONSTANTS:
    APP_CODE = "4ca99fa6b56cc2ba"
    SIGN_URL = "https://zonai.skland.com/api/v1/game/attendance"
    BINDING_URL = "https://zonai.skland.com/api/v1/game/player/binding"
    GRANT_CODE_URL = "https://as.hypergryph.com/user/oauth2/v2/grant"
    CRED_CODE_URL = "https://zonai.skland.com/api/v1/user/auth/generate_cred_by_code"

    @property
    def REQUEST_HEADERS_BASE(self) -> dict[str, str]:
        return {
            "User-Agent": "Skland/1.20.0 (com.hypergryph.skland; build:102000098; Android 29; ) Okhttp/4.11.0",
            "Accept-Encoding": "gzip",
            "Connection": "close",
            "Origin": "https://www.skland.com",
            "Referer": "https://www.skland.com/",
            "Content-Type": "application/json; charset=utf-8",
            "manufacturer": "HUAWEI",
            "os": "29",
        }

    @property
    def SIGN_HEADERS_BASE(self) -> dict[str, str]:
        return {"platform": "1", "timestamp": "", "dId": "d747e6d2fc869d30", "vName": "1.20.0"}

```

**Comment by yytphilip** [comment]
1. 是那串数字×
2. 客户端是1.20.0
3. 换了，但是无用×

也许是一直挂着签到，服务器IP被ban了？

**Comment by GuGuMur** [comment]
有可能欸，要不换下服务器/本地跑一下看看？

**Comment by yytphilip** [comment]
昨天开始忽然自己好了，突然签到成功，迷惑×联动隔壁问题应该是YJ的锅(
