### ISSUE TITLE
[Bug]: 插件无法正常加载，pydantic 读取 Config 时校验错误

### ISSUE THREAD

**Issue by Well2333** [GuGuMur/nonebot-plugin-skland-arksign#62]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读插件的 README
- [X] 我的Python版本满足>= 3.10
- [X] 我已经将插件和机器人环境依赖都安装到了推荐/最新版本
- [X] 我确定指令输入并无错误
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### 运行环境

Windows (64)

### Nonebot 2 版本

其它（请在下方说明）

### 重现步骤

插件无法正常加载，可能是与 pydantic 版本更新有关

### 期望的结果是什么？

*

### 实际的结果是什么？

*

### 日志记录（可选）

```python
09-22 00:14:29 [ERROR] nonebot | Failed to import "nonebot_plugin_skland_arksign"
Traceback (most recent call last):
  File "/home/well404/bots/bilichat/bot.py", line 30, in <module>
    nonebot.load_plugin("nonebot_plugin_skland_arksign")
  File "/home/well404/bots/bilichat/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 40, in load_plugin
    return manager.load_plugin(module_path)
> File "/home/well404/bots/bilichat/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 167, in load_plugin
    module = importlib.import_module(self._third_party_plugin_ids[name])
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/well404/bots/bilichat/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 255, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/well404/bots/bilichat/.venv/lib/python3.10/site-packages/nonebot_plugin_skland_arksign/__init__.py", line 13, in <module>
    from .command import skland as skland
  File "/home/well404/bots/bilichat/.venv/lib/python3.10/site-packages/nonebot_plugin_skland_arksign/command.py", line 15, in <module>
    from .sched import sched_sign
  File "/home/well404/bots/bilichat/.venv/lib/python3.10/site-packages/nonebot_plugin_skland_arksign/sched.py", line 11, in <module>
    from .signin import SignResult, run_signin
  File "/home/well404/bots/bilichat/.venv/lib/python3.10/site-packages/nonebot_plugin_skland_arksign/signin.py", line 14, in <module>
    from .config import plugin_config
  File "/home/well404/bots/bilichat/.venv/lib/python3.10/site-packages/nonebot_plugin_skland_arksign/config.py", line 47, in <module>
    plugin_config: Config = Config.parse_obj(get_driver().config)
  File "/home/well404/bots/bilichat/.venv/lib/python3.10/site-packages/pydantic/main.py", line 1072, in parse_obj
    return cls.model_validate(obj)
  File "/home/well404/bots/bilichat/.venv/lib/python3.10/site-packages/pydantic/main.py", line 509, in model_validate
    return cls.__pydantic_validator__.validate_python(
pydantic_core._pydantic_core.ValidationError: 1 validation error for Config
  Input should be a valid dictionary or instance of Config [type=model_type, input_value=Config(driver='~fastapi+~...lichat_neterror_retry=5), input_type=Config]
    For further information visit https://errors.pydantic.dev/2.6/v/model_type
```

### 补充说明（可选）

nonebot2 版本 2.3.3
pydantic 版本 2.6.1

**Comment by Well2333** [comment]
https://github.com/GuGuMur/nonebot-plugin-skland-arksign/blob/main/nonebot_plugin_skland_arksign/config.py#L55

经测试，将此行代码修改为

```
from nonebot import get_plugin_config

plugin_config: Config = get_plugin_config(Config)
```

即可解决此错误

**Comment by GuGuMur** [comment]
> ```python
>  File "/home/well404/bots/bilichat/.venv/lib/python3.10/site- packages/nonebot_plugin_skland_arksign/config.py", line 47, in <module>
>    plugin_config: Config = Config.parse_obj(get_driver().config)
> ```

但是 #56 就已经用了新用法了啊（

改了 #63

**Comment by Well2333** [comment]
我理解了，由于项目中锁定了pydantic的最新版

"pydantic>=2.9.2"

但是我的项目中部分依赖限制在 ＜=2.6.1，所以安装了旧版。

由于项目中未使用到2.0.0版本之后的后续添加的特性，因此为了兼容性，建议将版本限制改为

"pydantic>=2.0.0"

以避免出现依赖冲突的问题。
