### ISSUE TITLE
[Bug]: 0.7.2无法正常签到

### ISSUE THREAD

**Issue by Ra1n-qwq** [GuGuMur/nonebot-plugin-skland-arksign#65]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读插件的 README
- [X] 我的Python版本满足>= 3.10
- [X] 我已经将插件和机器人环境依赖都安装到了推荐/最新版本
- [X] 我确定指令输入并无错误
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### 运行环境

Linux

### Nonebot 2 版本

2.3.3

### 重现步骤

从昨天开始签到失败，相关bot服务部署在云服务器。
https://zonai.skland.com/api/v1/user/auth/generate_cred_by_code
这个签到接口好像被森空岛的waf拦截了，我用自己的电脑访问也会被拦截，应该是加了令牌限制。
![image](https://github.com/user-attachments/assets/9393e979-79d3-40b3-8822-70b39b84f6e9)

### 期望的结果是什么？

签到成功

### 实际的结果是什么？

[森空岛明日方舟签到器]执行定时任务！

签到失败：Client error '405 Not Allowed' for url 'https://zonai.skland.com/api/v1/user/auth/generate_cred_by_code'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405
----------
签到失败：Client error '405 Not Allowed' for url 'https://zonai.skland.com/api/v1/user/auth/generate_cred_by_code'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405

### 日志记录（可选）

```python
09-22 16:23:54 [ERROR] nonebot_plugin_skland_arksign | 签到失败：Client error '405 Not Allowed' for url 'https://zonai.skland.com/api/v1/user/auth/generate_cred_by_code'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405
Traceback (most recent call last):
  File "awabot/bot.py", line 38, in <module>
    nonebot.run(app="__mp_main__:app")
  File ".local/lib/python3.10/site-packages/nonebot/__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File ".local/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 186, in run
    uvicorn.run(
  File ".local/lib/python3.10/site-packages/uvicorn/main.py", line 569, in run
    server.run()
  File ".local/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File ".local/lib/python3.10/site-packages/nonebot/message.py", line 476, in check_and_run_matcher
    await _run_matcher(
  File ".local/lib/python3.10/site-packages/nonebot/message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File ".local/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File ".local/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 825, in simple_run
    await handler(
  File ".local/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File ".local/lib/python3.10/site-packages/nonebot_plugin_skland_arksign/command.py", line 281, in signin_all
    await sched_sign()
  File ".local/lib/python3.10/site-packages/nonebot_plugin_skland_arksign/sched.py", line 32, in sched_sign
    result = await run_signin(uid=sub.uid, token=sub.token)
> File ".local/lib/python3.10/site-packages/nonebot_plugin_skland_arksign/signin.py", line 168, in run_signin
    return await _run_signin(uid, token)
  File ".local/lib/python3.10/site-packages/nonebot_plugin_skland_arksign/signin.py", line 161, in _run_signin
    cred_resp = await get_cred_resp(grand_code)
  File ".local/lib/python3.10/site-packages/nonebot_plugin_skland_arksign/signin.py", line 91, in get_cred_resp
    response.raise_for_status()
  File ".local/lib/python3.10/site-packages/httpx/_models.py", line 763, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '405 Not Allowed' for url 'https://zonai.skland.com/api/v1/user/auth/generate_cred_by_code'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405
```

**Comment by GuGuMur** [comment]
yj重新把waf加回来了，在yj大发善心前还是先自己手动登app签到吧
